image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true

install:
  - ps: gitversion /output buildserver
  - ps: $env:APPVEYOR_BUILD_NUMBER = $env:GitVersion_CommitsSinceVersionSource
  - ps: $env:major_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:minor_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:release_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:APPVEYOR_BUILD_NUMBER"

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore "source\Common.sln"

build:
  project: source\Common.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: scripts\InstallTestAssemblies.bat

after_test:
  - cmd: scripts\UninstallTestAssemblies.bat

on_success:
  - ps: $xRevision = Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/Revision"
  - ps: $xRevision.Node.InnerText = $env:APPVEYOR_BUILD_NUMBER
  - ps: $xRevision.Node.OwnerDocument.Save($xRevision.Path)
  - ps: git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - ps: git config --global user.email "$env:github_email"
  - ps: git config --global user.name "$env:github_name"
  - git commit -m "Revision update by AppVeyor" -- version.props
  - git push --tags --force