image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true

install:
  - ps: gitversion /output buildserver
  - ps: $env:major_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:minor_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:release_version = $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:revision = $env:GitVersion_CommitsSinceVersionSource
  - ps: Update-AppveyorBuild -Version "$env:major_version.$env:$env:minor_version.$env:release_version.$env:revision"
  - ps: $xReleaseVersion = Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/ReleaseVersion"
  - ps: $xReleaseVersion.Node.InnerText = $env:release_version
  - ps: $xReleaseVersion.Node.OwnerDocument.Save($xReleaseVersion.Path)
  - ps: $xRevision = Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/Revision"
  - ps: $xRevision.Node.InnerText = $env:revision
  - ps: $xRevision.Node.OwnerDocument.Save($xRevision.Path)

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore "source\Common.sln"

build:
  project: source\Common.sln
  parallel: true
  verbosity: minimal

after_build:
  - cmd: scripts\InstallTestAssemblies.bat

after_test:
  - cmd: scripts\UninstallTestAssemblies.bat

artifacts:
- path: 'bin\Release\EnterpriseLibrary.Common.*.nupkg'
  name: 'EnterpriseLibrary.Common'