image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: $env:major_version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:minor_version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:release_version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:APPVEYOR_BUILD_NUMBER"

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore "source\Common.sln"

build:
  project: source\Common.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: %WINDIR%\Microsoft.NET\Framework\v4.0.30319\installutil "source\Tests\Common\bin\Release\net47\EnterpriseLibrary.Common.Tests.dll"

after_test:
- cmd: %WINDIR%\Microsoft.NET\Framework\v4.0.30319\installutil -u "source\Tests\Common\bin\Release\net47\EnterpriseLibrary.Common.Tests.dll"