image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: gitversion /output buildserver
  - ps: $env:APPVEYOR_BUILD_NUMBER = $env:GitVersion_CommitsSinceVersionSource
  - ps: $env:major_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:minor_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: $env:release_version = (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
  - ps: (Select-Xml -Path ".\version.props" -XPath "/Project/PropertyGroup/Revision" | Select-Object -ExpandProperty Node).InnerText = $env:APPVEYOR_BUILD_NUMBER
  - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:APPVEYOR_BUILD_NUMBER"

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore "source\Common.sln"

build:
  project: source\Common.sln
  parallel: true
  verbosity: minimal

after_build:
- cmd: scripts\InstallTestAssemblies.bat

after_test:
- cmd: scripts\UninstallTestAssemblies.bat

artifacts:
- path: version.props